import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import Headers from './header/page'

const dbHelvetica = localFont({
  src: '../public/fonts/db-helvethaica-x.ttf',
  variable: '--font-db-helvetica',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className={dbHelvetica.variable}>
      <body className={dbHelvetica.className}>
        <Headers />
        <div className="relative w-full h-auto pt-20 bg-background-white">
          {children}
        </div>
      </body>
    </html>
  );
}