import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import Headers from './header/header'

const dbHelvetica = localFont({
  src: '../public/fonts/db-helvethaica-x.ttf',
  variable: '--font-db-helvetica',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className={dbHelvetica.variable}>
      <body className={dbHelvetica.className}>
        <div className="flex flex-col">
          <Headers />
          <div className="h-20" />
          <div className="relative w-full bg-background-white overflow-x-hidden">
            {children}
          </div>

        </div>
      </body>
    </html>
  );
}